export const CANDIDATE_APPLIED_JOB = "CANDIDATE_APPLIED_JOB";
export const CANDIDATE_APPLIED_JOB_GET_PENDING =
  "CANDIDATE_APPLIED_JOB_GET_PENDING";
export const CANDIDATE_APPLIED_JOB_ERROR = "CANDIDATE_APPLIED_JOB_ERROR";