export const routeType = {
  COMPANY_JOBS_VIEW: "COMPANY_JOBS_VIEW",
  COMPANY_JOB_DETAIL_VIEW: "COMPANY_JOB_DETAIL_VIEW",
  COMPANY_REGISTER_VIEW: "COMPANY_REGISTER_VIEW",
  COMPANY_LOGIN_VIEW: "COMPANY_LOGIN_VIEW",

  CANDIDATE_LOGIN_VIEW: "CANDIDATE_LOGIN_VIEW",
  CANDIDATE_REGISTER_VIEW: "CANDIDATE_REGISTER_VIEW",
  CANDIDATE_UPLOAD_RESUME_VIEW: "CANDIDATE_UPLOAD_RESUME_VIEW",
  CANDIDATE_PROFILE_VIEW: "CANDIDATE_PROFILE_VIEW",
  CANDIDATE_COMPANY_JOBS_VIEW: "CANDIDATE_COMPANY_JOBS_VIEW",
  CANDIDATE_JOB_DETAIL_VIEW: "CANDIDATE_JOB_DETAIL_VIEW",
  CANDIDATE_DASHBOARD_VIEW: 'CANDIDATE_DASHBOARD_VIEW',
  
  TECHNICAL_TEST_VIEW: "TECHNICAL_TEST_VIEW",
  PERSONALITY_TEST_VIEW: "PERSONALITY_TEST_VIEW",
};
