export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGOUT_PENDING = "USER_LOGOUT_PENDING";
export const USER_REGISTER_PENDING = "USER_REGISTER_PENDING";
export const USER_ERROR = "USER_ERROR";
