export const COMPANY_JOBS = "COMPANY_JOBS";
export const CREATE_COMPANY_JOB = "CREATE_COMPANY_JOB";
export const COMPANY_JOBS_GET_PENDING = "COMPANY_JOBS_GET_PENDING";
export const COMPANY_JOBS_ADD_PENDING = "COMPANY_JOBS_ADD_PENDING";
export const COMPANY_JOB_ERROR = "COMPANY_JOB_ERROR";
